name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests ✅
        run: npm test

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CLOUD_RESUME_SECRET }}

      - name: Deploy to Azure Function
        run: |
          cd backend
          func azure functionapp publish counter2
